### ISSUE TITLE
Unable to read file

### ISSUE THREAD

**Issue by VCCICCV** [allan2/dotenvy#124]
My computer is Windows 11, but I see other people can use it，rustc 1.80.1
![image](https://github.com/user-attachments/assets/c20be5be-6ed7-47a2-a0c1-0b3ba1c25920)

```rust
use axum::{ routing::get, Router };
async fn hello()-> String{
    "hello".to_string()
}
use dotenvy::dotenv;
use std::env;
#[tokio::main]
async fn main() {
    dotenv().expect("Failed to load.env file ☹");

    let port = env::var("PORT").expect("Port not set ☹");
    println!("Port: {}", port);
    // for (key, value) in env::vars() {
    //     println!("{key}: {value}");
    // }

    let app = Router::new().route("/",get(hello));

    let listener = tokio::net::TcpListener::bind("0.0.0.0:8080").await.unwrap();

    axum::serve(listener, app).await.unwrap();
}
```
cargo.toml
```toml
axum = "0.7.5"
sea-orm = { version = "1.0.0", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
] }
tower-http = { version = "0.5", features = ["fs","trace"] }
tokio = { version = "1.40.0", features = ["full"] }
dotenvy = "0.15.7"
```
